    
 spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 56467678hjhikjoi7868324
            clientSecret: 28879b6bbf54ffff9a10dc01jjjjjjjjjjjjjjjj28bf13061278a21eb0095
  resource:
        user-info-uri: https://api.github.com/user
